use rayon::prelude::*;
use rustc_hash::FxHashSet;

use crate::path_utils::relativize;

#[derive(Default)]
pub(super) struct GeneratedSourceIndexes {
    pub(super) sources: FxHashSet<String>,
    pub(super) additional_surface_sources: FxHashSet<String>,
}

#[derive(Clone, Copy)]
enum GeneratedSourceKind {
    Established,
    AdditionalSurface,
}

pub(super) fn generated_source_indexes(
    families: &[nose_detect::RefactorFamily],
) -> GeneratedSourceIndexes {
    let cwd = std::env::current_dir().ok();
    let mut generated = GeneratedSourceIndexes::default();
    let files = families
        .iter()
        .flat_map(|family| {
            family
                .locations
                .iter()
                .map(|location| location.file.as_str())
        })
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .map(str::to_string)
        .collect::<Vec<_>>();
    let generated_files = files
        .into_par_iter()
        .filter_map(|path| generated_source_kind(&path).map(|kind| (path, kind)))
        .collect::<Vec<_>>();
    for (path, kind) in generated_files {
        let index = match kind {
            GeneratedSourceKind::Established => &mut generated.sources,
            GeneratedSourceKind::AdditionalSurface => &mut generated.additional_surface_sources,
        };
        index.insert(path.clone());
        if let Some(cwd) = &cwd {
            index.insert(relativize(&path, cwd));
        }
    }
    generated
}

fn generated_source_kind(file: &str) -> Option<GeneratedSourceKind> {
    if file.ends_with(".css") {
        let text = std::fs::read_to_string(file).ok()?;
        return (text.lines().take(8).any(is_generated_header_line)
            || looks_compiled_css(file, &text))
        .then_some(GeneratedSourceKind::Established);
    }
    let head = bounded_source_head(file)?;
    if source_head_has_generated_header(&head) {
        Some(GeneratedSourceKind::Established)
    } else if head_has_jazzy_generated_provenance(file, &head) {
        Some(GeneratedSourceKind::AdditionalSurface)
    } else {
        None
    }
}

const GENERATED_HEADER_READ_BYTES: u64 = 64 * 1024;

fn bounded_source_head(file: &str) -> Option<Vec<u8>> {
    let Ok(mut file) = std::fs::File::open(file) else {
        return None;
    };
    let mut head = Vec::new();
    let mut limited = std::io::Read::take(&mut file, GENERATED_HEADER_READ_BYTES);
    std::io::Read::read_to_end(&mut limited, &mut head)
        .ok()
        .map(|_| head)
}

fn source_head_has_generated_header(head: &[u8]) -> bool {
    std::str::from_utf8(head)
        .ok()
        .is_some_and(|text| text.lines().take(8).any(is_generated_header_line))
}

/// Jazzy output carries two independent provenance classes in the bounded file head: its
/// asset and an Apple/Dash symbol anchor. Requiring both classes in every HTML member keeps
/// partial generation and ordinary hand-written HTML fail-open; the caller supplies the
/// all-members quantifier.
pub(crate) fn head_has_jazzy_generated_provenance(file: &str, head: &[u8]) -> bool {
    if !std::path::Path::new(file)
        .extension()
        .is_some_and(|extension| extension.eq_ignore_ascii_case("html"))
    {
        return false;
    }
    let mut lower = head.to_vec();
    lower.make_ascii_lowercase();
    let has = |token: &[u8]| lower.windows(token.len()).any(|window| window == token);
    (has(b"jazzy.css") || has(b"jazzy.js"))
        && (has(b"class=\"dashanchor\"") || has(b"//apple_ref/"))
}

fn is_generated_header_line(line: &str) -> bool {
    let line = line.trim().to_ascii_lowercase();
    line.contains("@generated")
        || line.contains("generated by")
        || line.contains("code generated")
        || line.contains("automatically generated")
        || line.contains("auto-generated")
        || line.contains("autogenerated")
        || (line.contains("generated") && line.contains("do not edit"))
}

/// A compiled/distributed stylesheet is a build artifact, not hand-edited source. Detect
/// preserved license/version banners, source maps, and minified paths. The frontend gold
/// set measured 147 generated demotions with no worthy family.
pub(crate) fn looks_compiled_css(file: &str, text: &str) -> bool {
    if !file.ends_with(".css") {
        return false;
    }
    if file
        .split('/')
        .any(|segment| matches!(segment, "scss" | "sass" | "less" | "styl"))
    {
        return false;
    }
    if file.ends_with(".min.css") || std::path::Path::new(&format!("{file}.map")).exists() {
        return true;
    }
    for line in text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .take(8)
    {
        if line.starts_with("/*!")
            || (line.starts_with("@charset") && line.contains("/*!"))
            || (line.starts_with("/*") && has_version_tag(line))
        {
            return true;
        }
    }
    text.lines()
        .rev()
        .filter(|line| !line.trim().is_empty())
        .take(3)
        .any(|line| line.contains("sourceMappingURL"))
}

/// A `vN.N`(.N) version token: a release marker of a distributed stylesheet.
pub(crate) fn has_version_tag(value: &str) -> bool {
    let bytes = value.as_bytes();
    for index in 0..bytes.len().saturating_sub(2) {
        if (bytes[index] | 0x20) == b'v' && bytes[index + 1].is_ascii_digit() {
            let mut end = index + 1;
            while end < bytes.len() && bytes[end].is_ascii_digit() {
                end += 1;
            }
            if end + 1 < bytes.len() && bytes[end] == b'.' && bytes[end + 1].is_ascii_digit() {
                return true;
            }
        }
    }
    false
}
