use super::*;

pub(in crate::packs::compiled) const SEQUENCE_HOF_ADAPTER_PROTOCOL_LANGUAGES: &[&str] =
    &["rust", "swift", "ruby"];
pub(in crate::packs::compiled) const SEQUENCE_HOF_ADAPTER_PROTOCOL_PACKAGES: &[&str] =
    &["core::iter", "Swift.Collection", "Enumerable"];
pub(in crate::packs::compiled) const SEQUENCE_HOF_ADAPTER_PROTOCOL_PRODUCER_IDS: &[&str] =
    &[SEQUENCE_HOF_ADAPTER_PROTOCOL_PRODUCER_ID];
pub(in crate::packs::compiled) const SEQUENCE_HOF_ADAPTER_PROTOCOL_CONTRACT_IDS: &[&str] =
    &[SEQUENCE_HOF_ADAPTER_CONTRACT_ID];
pub(in crate::packs::compiled) const SEQUENCE_HOF_ADAPTER_PROTOCOL_CONFORMANCE_REFS: &[&str] = &[
    "rust-iterator-hof-map-positive",
    "rust-iterator-hof-filter-positive",
    "rust-iterator-hof-filter-map-positive",
    "rust-iterator-hof-flat-map-positive",
    "rust-iterator-hof-any-terminal-positive",
    "rust-iterator-hof-all-terminal-positive",
    "rust-iterator-hof-count-terminal-positive",
    "rust-iterator-hof-custom-method-hard-negative",
    "rust-iterator-hof-missing-receiver-proof-hard-negative",
    "rust-iterator-hof-eager-callback-hard-negative",
    "rust-iterator-hof-missing-terminal-proof-hard-negative",
    "rust-iterator-hof-one-shot-reuse-hard-negative",
    "rust-iterator-hof-collect-vec-hard-negative",
    "rust-iterator-hof-find-unsupported-hard-negative",
    "swift-sequence-hof-map-positive",
    "swift-sequence-hof-filter-positive",
    "swift-sequence-hof-compact-map-positive",
    "swift-sequence-hof-flat-map-positive",
    "swift-sequence-hof-flat-map-identity-positive",
    "swift-sequence-hof-flat-map-cross-product-positive",
    "swift-sequence-hof-set-order-hard-negative",
    "swift-sequence-hof-dictionary-order-hard-negative",
    "swift-sequence-hof-lazy-hard-negative",
    "swift-sequence-hof-throwing-closure-hard-negative",
    "swift-sequence-hof-mutating-closure-hard-negative",
    "swift-sequence-hof-any-sequence-reuse-hard-negative",
    "swift-sequence-hof-compact-map-changed-drop-hard-negative",
    "swift-sequence-hof-compact-map-changed-value-hard-negative",
    "swift-sequence-hof-compact-map-wrong-source-hard-negative",
    "swift-sequence-hof-compact-map-wrong-option-channel-hard-negative",
    "swift-sequence-hof-compact-map-effectful-closure-hard-negative",
    "swift-sequence-hof-compact-map-custom-overload-hard-negative",
    "swift-sequence-hof-compact-map-custom-nominal-receiver-hard-negative",
    "swift-sequence-hof-compact-map-optional-emitted-value-hard-negative",
    "swift-sequence-hof-compact-map-custom-nil-literal-hard-negative",
    "swift-sequence-hof-compact-map-derived-source-hard-negative",
    "swift-sequence-hof-compact-map-retroactive-nil-conformance-hard-negative",
    "swift-sequence-hof-flat-map-zero-depth-hard-negative",
    "swift-sequence-hof-flat-map-derived-outer-hard-negative",
    "swift-sequence-hof-flat-map-derived-inner-hard-negative",
    "swift-sequence-hof-flat-map-scalar-result-hard-negative",
    "swift-sequence-hof-flat-map-recursive-depth-hard-negative",
    "swift-sequence-hof-flat-map-effectful-closure-hard-negative",
    "swift-sequence-hof-flat-map-reordered-traversal-hard-negative",
    "swift-sequence-hof-flat-map-changed-value-hard-negative",
    "swift-sequence-hof-flat-map-wrong-source-hard-negative",
    "swift-sequence-hof-flat-map-custom-overload-hard-negative",
    "swift-sequence-hof-flat-map-custom-inner-map-hard-negative",
    "ruby-enumerable-hof-map-positive",
    "ruby-enumerable-hof-collect-positive",
    "ruby-enumerable-hof-select-positive",
    "ruby-enumerable-hof-filter-positive",
    "ruby-enumerable-hof-reject-positive",
    "ruby-enumerable-hof-no-block-hard-negative",
    "ruby-enumerable-hof-lazy-enumerator-hard-negative",
    "ruby-enumerable-hof-framework-relation-hard-negative",
    "ruby-enumerable-hof-custom-method-hard-negative",
    "ruby-enumerable-hof-hash-order-hard-negative",
    "ruby-enumerable-hof-set-order-hard-negative",
    "ruby-enumerable-hof-mutating-block-hard-negative",
    "ruby-enumerable-hof-flat-map-unsupported-hard-negative",
];
