//! Semantic pack manifest loading and provenance summaries.
//!
//! Loading a manifest is an explicit opt-in metadata path. External packs do not
//! emit evidence or approve exact results from this module; consumers must still
//! require occurrence evidence and kernel-owned admission checks.

use crate::{
    pack_facing_value_laws, BuiltinTypeDomainAliasContract, PackTrust, BUILTIN_COMPAT_PACK_ID,
    BUILTIN_METHOD_CALL_CONTRACT_ID, BUILTIN_METHOD_CALL_PROTOCOL_PACK_ID,
    BUILTIN_METHOD_CALL_PROTOCOL_PRODUCER_ID, CSS_LANGUAGE_CORE_PRODUCER_ID, CSS_LANGUAGE_PACK_ID,
    CSS_SOURCE_FACT_PRODUCER_ID, C_LANGUAGE_CORE_PRODUCER_ID, C_LANGUAGE_PACK_ID,
    C_SOURCE_FACT_PRODUCER_ID, C_UNSIGNED_32_CAST_SOURCE_PRODUCER_ID,
    FREE_FUNCTION_BUILTIN_CONTRACT_ID, FREE_FUNCTION_BUILTIN_PROTOCOL_PACK_ID,
    FREE_FUNCTION_BUILTIN_PROTOCOL_PRODUCER_ID, FREE_FUNCTION_HOF_CONTRACT_ID,
    GO_LANGUAGE_CORE_PRODUCER_ID, GO_LANGUAGE_PACK_ID, GO_SOURCE_FACT_PRODUCER_ID,
    GO_STDLIB_NAMESPACE_CALL_CONTRACT_ID, GO_STDLIB_NAMESPACE_CALL_PACK_ID,
    GO_STDLIB_NAMESPACE_CALL_PRODUCER_ID, HTML_EMBEDDED_LANGUAGE_CORE_PRODUCER_ID,
    HTML_EMBEDDED_LANGUAGE_PACK_ID, HTML_EMBEDDED_SOURCE_FACT_PRODUCER_ID,
    ITERATOR_IDENTITY_ADAPTER_CONTRACT_ID, ITERATOR_IDENTITY_ADAPTER_PACK_ID,
    ITERATOR_IDENTITY_ADAPTER_PRODUCER_ID, JAVA_GUAVA_IMMUTABLE_COLLECTION_FACTORY_PACK_ID,
    JAVA_GUAVA_IMMUTABLE_COLLECTION_FACTORY_PRODUCER_ID, JAVA_GUAVA_IMMUTABLE_LIST_OF_CONTRACT_ID,
    JAVA_GUAVA_IMMUTABLE_MAP_OF_CONTRACT_ID, JAVA_GUAVA_IMMUTABLE_SET_OF_CONTRACT_ID,
    JAVA_LANGUAGE_CORE_PRODUCER_ID, JAVA_LANGUAGE_PACK_ID, JAVA_SOURCE_FACT_PRODUCER_ID,
    JAVA_STDLIB_COLLECTION_CONSTRUCTOR_EMPTY_LIST_CONTRACT_ID,
    JAVA_STDLIB_COLLECTION_CONSTRUCTOR_PACK_ID, JAVA_STDLIB_COLLECTION_CONSTRUCTOR_PRODUCER_ID,
    JAVA_STDLIB_COLLECTION_FACTORY_ARRAYS_AS_LIST_CONTRACT_ID,
    JAVA_STDLIB_COLLECTION_FACTORY_COLLECTIONS_EMPTY_LIST_CONTRACT_ID,
    JAVA_STDLIB_COLLECTION_FACTORY_COLLECTIONS_EMPTY_SET_CONTRACT_ID,
    JAVA_STDLIB_COLLECTION_FACTORY_COLLECTIONS_SINGLETON_CONTRACT_ID,
    JAVA_STDLIB_COLLECTION_FACTORY_COLLECTIONS_SINGLETON_LIST_CONTRACT_ID,
    JAVA_STDLIB_COLLECTION_FACTORY_LIST_OF_CONTRACT_ID, JAVA_STDLIB_COLLECTION_FACTORY_PACK_ID,
    JAVA_STDLIB_COLLECTION_FACTORY_PRODUCER_ID, JAVA_STDLIB_COLLECTION_FACTORY_SET_OF_CONTRACT_ID,
    JAVA_STDLIB_MAP_ENTRY_CONTRACT_ID, JAVA_STDLIB_MAP_ENTRY_PACK_ID,
    JAVA_STDLIB_MAP_ENTRY_PRODUCER_ID, JAVA_STDLIB_MAP_FACTORY_COLLECTIONS_EMPTY_MAP_CONTRACT_ID,
    JAVA_STDLIB_MAP_FACTORY_COLLECTIONS_SINGLETON_MAP_CONTRACT_ID,
    JAVA_STDLIB_MAP_FACTORY_OF_CONTRACT_ID, JAVA_STDLIB_MAP_FACTORY_OF_ENTRIES_CONTRACT_ID,
    JAVA_STDLIB_MAP_FACTORY_PACK_ID, JAVA_STDLIB_MAP_FACTORY_PRODUCER_ID, JAVA_STDLIB_MATH_PACK_ID,
    JAVA_STDLIB_MATH_PRODUCER_ID, JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_CONTRACT_ID,
    JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_PACK_ID,
    JAVA_STDLIB_STATIC_COLLECTION_ADAPTER_PRODUCER_ID,
    JS_LIKE_BUILTIN_ARRAY_BOOL_REDUCTION_CONTRACT_ID, JS_LIKE_BUILTIN_ARRAY_FROM_CONTRACT_ID,
    JS_LIKE_BUILTIN_ARRAY_HOF_CONTRACT_ID, JS_LIKE_BUILTIN_ARRAY_IS_ARRAY_CONTRACT_ID,
    JS_LIKE_BUILTIN_ARRAY_PACK_ID, JS_LIKE_BUILTIN_ARRAY_PRODUCER_ID,
    JS_LIKE_BUILTIN_BOOLEAN_CONTRACT_ID, JS_LIKE_BUILTIN_BOOLEAN_PACK_ID,
    JS_LIKE_BUILTIN_BOOLEAN_PRODUCER_ID, JS_LIKE_BUILTIN_COLLECTION_CONSTRUCTOR_PACK_ID,
    JS_LIKE_BUILTIN_COLLECTION_CONSTRUCTOR_PRODUCER_ID,
    JS_LIKE_BUILTIN_MAP_CONSTRUCTOR_CONTRACT_ID, JS_LIKE_BUILTIN_PROMISE_PACK_ID,
    JS_LIKE_BUILTIN_PROMISE_PRODUCER_ID, JS_LIKE_BUILTIN_PROMISE_RESOLVE_CONTRACT_ID,
    JS_LIKE_BUILTIN_PROMISE_THEN_CONTRACT_ID, JS_LIKE_BUILTIN_REGEX_PACK_ID,
    JS_LIKE_BUILTIN_REGEX_PRODUCER_ID, JS_LIKE_BUILTIN_REGEX_TEST_CONTRACT_ID,
    JS_LIKE_BUILTIN_SET_CONSTRUCTOR_CONTRACT_ID,
    JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_FIND_INDEX_CONTRACT_ID,
    JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_INDEX_OF_CONTRACT_ID,
    JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_PACK_ID,
    JS_LIKE_BUILTIN_STATIC_INDEX_MEMBERSHIP_PRODUCER_ID, JS_TS_LANGUAGE_CORE_PRODUCER_ID,
    JS_TS_LANGUAGE_PACK_ID, JS_TS_SOURCE_FACT_PRODUCER_ID, MAP_GET_CONTRACT_ID,
    MAP_GET_DEFAULT_CONTRACT_ID, MAP_GET_DEFAULT_PROTOCOL_PACK_ID,
    MAP_GET_DEFAULT_PROTOCOL_PRODUCER_ID, MAP_GET_PROTOCOL_PACK_ID, MAP_GET_PROTOCOL_PRODUCER_ID,
    MAP_KEY_VIEW_COLLECTION_CONTRACT_ID, MAP_KEY_VIEW_ITERATOR_CONTRACT_ID,
    MAP_KEY_VIEW_PROTOCOL_PACK_ID, MAP_KEY_VIEW_PROTOCOL_PRODUCER_ID,
    PROPERTY_BUILTIN_IS_EMPTY_CONTRACT_ID, PROPERTY_BUILTIN_LEN_CONTRACT_ID,
    PROPERTY_BUILTIN_PROTOCOL_PACK_ID, PROPERTY_BUILTIN_PROTOCOL_PRODUCER_ID,
    PYTHON_BUILTIN_COLLECTION_FACTORY_CONTRACT_ID, PYTHON_BUILTIN_COLLECTION_FACTORY_PACK_ID,
    PYTHON_BUILTIN_COLLECTION_FACTORY_PRODUCER_ID, PYTHON_ITERATOR_BUILTIN_CONTRACT_ID,
    PYTHON_ITERATOR_BUILTIN_PROTOCOL_PACK_ID, PYTHON_ITERATOR_BUILTIN_PROTOCOL_PRODUCER_ID,
    PYTHON_LANGUAGE_CORE_PRODUCER_ID, PYTHON_LANGUAGE_PACK_ID, PYTHON_SOURCE_FACT_PRODUCER_ID,
    PYTHON_STDLIB_COLLECTION_FACTORY_CONTRACT_ID, PYTHON_STDLIB_COLLECTION_FACTORY_PACK_ID,
    PYTHON_STDLIB_COLLECTION_FACTORY_PRODUCER_ID, PYTHON_STDLIB_MATH_PACK_ID,
    PYTHON_STDLIB_MATH_PRODUCER_ID, PYTHON_STDLIB_MATH_PROD_CONTRACT_ID,
    PYTHON_STDLIB_TYPE_DOMAIN_ALIAS_CONTRACTS, PYTHON_STDLIB_TYPE_DOMAIN_PACK_ID,
    RECEIVER_MEMBERSHIP_CONTRACT_ID, RECEIVER_MEMBERSHIP_PROTOCOL_PACK_ID,
    RECEIVER_MEMBERSHIP_PROTOCOL_PRODUCER_ID, RUBY_LANGUAGE_CORE_PRODUCER_ID,
    RUBY_LANGUAGE_PACK_ID, RUBY_SOURCE_FACT_PRODUCER_ID, RUBY_STDLIB_SET_CONTRACT_ID,
    RUBY_STDLIB_SET_PACK_ID, RUBY_STDLIB_SET_PRODUCER_ID, RUST_LANGUAGE_CORE_PRODUCER_ID,
    RUST_LANGUAGE_PACK_ID, RUST_SOURCE_FACT_PRODUCER_ID,
    RUST_STDLIB_COLLECTION_FACTORY_CONTRACT_ID, RUST_STDLIB_COLLECTION_FACTORY_PACK_ID,
    RUST_STDLIB_COLLECTION_FACTORY_PRODUCER_ID, RUST_STDLIB_INTEGER_METHOD_PACK_ID,
    RUST_STDLIB_INTEGER_METHOD_PRODUCER_ID, RUST_STDLIB_MAP_FACTORY_CONTRACT_ID,
    RUST_STDLIB_MAP_FACTORY_PACK_ID, RUST_STDLIB_MAP_FACTORY_PRODUCER_ID,
    RUST_STDLIB_OPTION_AND_THEN_CONTRACT_ID, RUST_STDLIB_OPTION_NONE_CONTRACT_ID,
    RUST_STDLIB_OPTION_PACK_ID, RUST_STDLIB_OPTION_PRODUCER_ID,
    RUST_STDLIB_OPTION_SOME_CONTRACT_ID, RUST_STDLIB_RESULT_ERR_CONTRACT_ID,
    RUST_STDLIB_RESULT_IS_ERR_CONTRACT_ID, RUST_STDLIB_RESULT_IS_OK_CONTRACT_ID,
    RUST_STDLIB_RESULT_OK_CONTRACT_ID, RUST_STDLIB_RESULT_PACK_ID, RUST_STDLIB_RESULT_PRODUCER_ID,
    RUST_STDLIB_VEC_MACRO_CONTRACT_ID, RUST_STDLIB_VEC_NEW_CONTRACT_ID, RUST_STDLIB_VEC_PACK_ID,
    RUST_STDLIB_VEC_PRODUCER_ID, SCALAR_INTEGER_METHOD_ABS_CONTRACT_ID,
    SCALAR_INTEGER_METHOD_CLAMP_CONTRACT_ID, SCALAR_INTEGER_METHOD_MAX_CONTRACT_ID,
    SCALAR_INTEGER_METHOD_MIN_CONTRACT_ID, SEQUENCE_HOF_ADAPTER_CONTRACT_ID,
    SEQUENCE_HOF_ADAPTER_PROTOCOL_PACK_ID, SEQUENCE_HOF_ADAPTER_PROTOCOL_PRODUCER_ID,
    STRING_AFFIX_PREDICATE_CONTRACT_ID, STRING_AFFIX_PREDICATE_PROTOCOL_PACK_ID,
    STRING_AFFIX_PREDICATE_PROTOCOL_PRODUCER_ID, SWIFT_LANGUAGE_CORE_PRODUCER_ID,
    SWIFT_LANGUAGE_PACK_ID, SWIFT_SOURCE_FACT_PRODUCER_ID, SWIFT_STDLIB_COLLECTION_FACTORY_PACK_ID,
    VALUE_GRAPH_LAW_PACK_ID,
};
#[cfg(test)]
use crate::{
    FIRST_PARTY_PACK_ID, FIRST_PARTY_VALUE_LAW_PACK_ID,
    SWIFT_STDLIB_COLLECTION_FACTORY_ARRAY_CONTRACT_ID, SWIFT_STDLIB_COLLECTION_FACTORY_PRODUCER_ID,
    SWIFT_STDLIB_COLLECTION_FACTORY_SET_CONTRACT_ID,
    SWIFT_STDLIB_DICTIONARY_UNIQUE_KEYS_CONTRACT_ID,
};
use nose_il::stable_symbol_hash;
use serde::Deserialize;
use std::path::PathBuf;
mod compiled;
mod conformance;
mod evidence_index;
mod exact_registry;
mod external;
mod loading;
mod lock;
mod manifest;
mod model;
mod near_registry;
mod receipt;
mod result_domain_semantics;
mod set;
mod v1;
mod validation;
pub use compiled::{
    builtin_compat_semantic_pack, builtin_pack_descriptor, builtin_pack_descriptors,
    first_party_semantic_pack, first_party_value_law_pack, python_stdlib_type_domain_pack,
    value_graph_law_pack, BuiltinLanguageBinding, BuiltinPackDescriptor,
};
pub use conformance::{
    SemanticPackConformanceManifest, SemanticPackConformanceReport,
    SemanticPackExecutableConformanceCheck, SemanticPackExecutableConformanceIssue,
    SemanticPackExecutableOracle, SemanticPackFixtureCheck, SemanticPackFixtureIssue,
    SemanticPackFixtureKind,
};
pub use evidence_index::{
    SemanticPackDependencyEvidence, SemanticPackDependencyEvidenceId, SemanticPackDependencySource,
    SemanticPackEvidenceBlocker, SemanticPackEvidenceIndex, SemanticPackEvidenceRow,
    SemanticPackOccurrenceEvidence,
};
pub use exact_registry::{
    SemanticPackExternalExactPackCounts, SemanticPackExternalExactProvenance,
    SemanticPackExternalExactRegistry, SemanticPackExternalExactReport,
};
pub use external::{
    ExternalContractRow, ExternalEvidenceProducerRow, ExternalInfluenceBlocker,
    ExternalInfluencePreflightReport, ExternalRowConflict, ExternalRowConflictReport,
    ExternalRowInfluencePreflight, ExternalRowKind, ExternalValueLawRow,
    SemanticPackRequirementSummary,
};
pub use loading::{
    check_semantic_pack_conformance, discover_manifest_paths, load_local_manifest,
    SemanticPackLoadError,
};
pub use lock::{
    create_project_lock, validate_project_lock, SemanticPackLockError, SemanticPackLockOptions,
    SemanticPackLockedFile, SemanticPackProjectLockSummary, SemanticPackV1Authorization,
    ValidatedSemanticPackProjectLock, SEMANTIC_PACK_LOCK_API_VERSION_V1,
};
use manifest::*;
pub use model::{
    semantic_pack_hash, SemanticPackAnchor, SemanticPackChannel, SemanticPackCounts,
    SemanticPackInfluence, SemanticPackKind, SemanticPackProofStatus, SemanticPackSource,
    SemanticPackSummary,
};
use model::{SemanticPackSchemaVersion, SemanticPackStatus};
pub use near_registry::{
    SemanticPackNearDependency, SemanticPackNearPackCounts, SemanticPackNearProtocol,
    SemanticPackNearProvenance, SemanticPackNearRegistry, SemanticPackNearReport,
};
pub use receipt::{
    read_semantic_pack_conformance_receipt, resolve_fixture_path, semantic_pack_file_digest,
    semantic_pack_fixture_digest, validate_semantic_pack_conformance_receipt,
    SemanticPackConformanceReceiptFixture, SemanticPackConformanceReceiptRow,
    SemanticPackConformanceReceiptV1, SemanticPackV1ObservedExpectation,
    MAX_SEMANTIC_PACK_DEPENDENCY_BYTES, MAX_SEMANTIC_PACK_FIXTURE_BYTES,
    MAX_SEMANTIC_PACK_FIXTURE_FILES, SEMANTIC_PACK_EXACT_KERNEL_CAPABILITY_V1,
    SEMANTIC_PACK_RECEIPT_API_VERSION_V1,
};
pub use set::SemanticPackSet;
use v1::{compile_manifest_v1, SemanticPackManifestV1};
pub use v1::{
    CompiledSemanticPackV1, SemanticPackV1Anchor, SemanticPackV1Arity, SemanticPackV1ArityKind,
    SemanticPackV1Call, SemanticPackV1CallShape, SemanticPackV1Channel, SemanticPackV1Conformance,
    SemanticPackV1ConformanceFixture, SemanticPackV1Contract, SemanticPackV1Coordinate,
    SemanticPackV1DemandProfile, SemanticPackV1EffectProfile, SemanticPackV1ExceptionProfile,
    SemanticPackV1Expectation, SemanticPackV1FixtureKind, SemanticPackV1IdentityProfile,
    SemanticPackV1Import, SemanticPackV1ImportRole, SemanticPackV1Language, SemanticPackV1Matcher,
    SemanticPackV1MutationProfile, SemanticPackV1Package, SemanticPackV1PackageCoordinate,
    SemanticPackV1PackageEcosystem, SemanticPackV1Profiles, SemanticPackV1ProtocolOperation,
    SemanticPackV1ReceiverRole, SemanticPackV1ResultDomain, SEMANTIC_PACK_API_VERSION_V1,
};

pub const SEMANTIC_PACK_API_VERSION: &str = "nose.semantic-pack.v0";
pub const SUPPORTED_SEMANTIC_PACK_API_VERSIONS: &[&str] =
    &[SEMANTIC_PACK_API_VERSION, SEMANTIC_PACK_API_VERSION_V1];

const ALLOWED_REQUIREMENT_PREFIXES: &[&str] = &[
    "Source.",
    "Symbol.",
    "Import.",
    "Domain.",
    "Type.",
    "Guard.",
    "Place.",
    "Effect.",
    "LibraryApi.",
    "CallTarget.",
    "SequenceSurface.",
    "nose.",
];

#[cfg(test)]
mod tests;
